# -*- coding: utf-8 -*-
"""CODE&VISUALS-Customer Lifecycle Intelligence: A Predictive Framework for Churn Mitigation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptbOVWOMKKmQeN3XNPFoTAlYTzGeFxZq

# Customer Lifecycle Intelligence: A Predictive Framework for Churn Mitigation

# **STEP 1**: IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, RepeatedStratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report, roc_auc_score

"""# STEP 2 : LOAD DATA"""

# Load data
Telcom = pd.read_csv("telecom_churn_data_FT.csv")

"""# MELT DATASET FROM WIDE TO LONG"""

# Identify 'static' columns (like mobile_number) that don't change month-to-month
id_vars = [col for col in Telcom.columns if not col.endswith(('_6','_7','_8','_9'))]

# Unpivot the data from wide to long format so each metric/month pair is in one row
Telcom_long = pd.melt(
    Telcom,
    id_vars=id_vars,
    var_name='feature_month',
    value_name='value'
)

import re

# 1. Downcast to save RAM
Telcom = Telcom.apply(pd.to_numeric, errors='ignore', downcast='float')

# 2. Identify only the essential ID
id_vars = ['mobile_number']

# 3. Melt
Telcom_long = Telcom.melt(id_vars=id_vars, var_name='original', value_name='value')

# 4. Optimized Extraction
def get_parts(s):
    match = re.search(r'(.+)_([6-9])$', s)
    if match:
        return match.group(1), match.group(2)
    return s, 'total'

parts = Telcom_long['original'].apply(get_parts)
Telcom_long['feature'], Telcom_long['month'] = zip(*parts)

# 5. Pivot - The efficient way
Telcom_final = Telcom_long.pivot(
    index=['mobile_number', 'month'],
    columns='feature',
    values='value'
).reset_index()

# 6. Final Cleanup
Telcom_final.columns.name = None
print("Final Shape:", Telcom_final.shape)
print(Telcom_final.head())

"""#STEP 3: CHECKING NUMBER OF COLUMNS"""

# Total columns
cols = Telcom.columns

# 1. Columns containing "mou"
mou_cols = [col for col in cols if "mou" in col.lower()]
print("MOU columns:", len(mou_cols))

# 2. Columns containing month info
month_patterns = ['_6', '_7', '_8', '_9', 'jun', 'jul', 'aug', 'sep']

month_cols = [col for col in cols if any(m in col.lower() for m in month_patterns)]
print("Month columns:", len(month_cols))

# 3. Columns containing BOTH "mou" and month
mou_month_cols = [col for col in mou_cols if any(m in col.lower() for m in month_patterns)]
print("MOU + Month columns:", len(mou_month_cols))

# 4. Total Number of columns
print("Total Number of Columns",len(Telcom.columns))

"""# STEP 4: DROPING TOTAL ROWS"""

# CLEANUP & COLUMN VERIFICATION
if 'Month' in Telcom_final.columns:
    Telcom_final = Telcom_final[Telcom_final['Month'] != 'total'].copy()
    print("Filtered 'total' rows successfully.")
else:
    print("Warning: 'Month' column not found. Check capitalization!")

print("\n--- Current Columns ---")
print(Telcom_final.columns.tolist())

"""# STEP 5: RENAMING MY NEW COLUMNS"""

rename_dict = {
    'circle_id': 'service_area_id',
    'loc_og_mou': 'local_out_min',
    'std_og_mou': 'std_out_min',
    'loc_ic_mou': 'local_in_min',
    'last_date_of_month': 'last_day_month',
    'arpu': 'avg_revenue_per_user',
    'onnet_mou': 'within_network_calls',
    'offnet_mou': 'other_network_calls',
    'roam_ic_mou': 'roam_incoming',
    'roam_og_mou': 'roam_outgoing',
    'loc_og_t2t_mou': 'local_out_same_net',
    'loc_og_t2m_mou': 'local_out_other_net',
    'loc_og_t2f_mou': 'local_out_fixedline',
    'loc_og_t2c_mou': 'customer_care_min',
    'total_og_mou': 'total_outgoing_min',
    'std_og_t2t_mou': 'std_out_same_net',
    'std_og_t2m_mou': 'std_out_other_net',
    'std_og_t2f_mou': 'std_out_fixedline',
    'isd_og_mou': 'intl_out_min',
    'spl_og_mou': 'special_out_min',
    'og_others': 'other_outgoing',
    'total_rech_num': 'total_recharges',
    'total_rech_amt': 'total_recharge_amt',
    'max_rech_amt': 'max_recharge_amt',
    'date_of_last_rech': 'date_last_recharge',
    'last_day_rch_amt': 'last_day_recharge_amt',
    'vol_2g_mb': 'data_2g_mb',
    'vol_3g_mb': 'data_3g_mb',
}

Telcom_final.rename(columns=rename_dict, inplace=True)


#  View Results

print(" Total columns:", len(Telcom_final.columns))
print("\n Column names:\n")
for col in Telcom_final.columns:
    print(col)

print("\n Preview of dataset:\n")
print(Telcom_final.head())

print("\n Dataset info:\n")
print(Telcom_final.info())

"""# STEP 6: DATA PREPARATION"""

Telcom = Telcom_final.copy()

"""# STEP 7: HANDLING MISSING VALUES"""

# 1. Dropping rows that are mostly empty
# We use .copy() to ensure we aren't working on a "slice" of the old data
row_missing_pct = (Telcom.isnull().sum(axis=1) / Telcom.shape[1]) * 100
Telcom = Telcom[row_missing_pct <= 80].copy()

# 2. Separate column types
# We use .tolist() to make iterating cleaner
numeric_cols = Telcom.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = Telcom.select_dtypes(include=['object']).columns.tolist()

# 3. Fill numeric with median
# Instead of a loop, we can do this in one efficient line
Telcom[numeric_cols] = Telcom[numeric_cols].fillna(Telcom[numeric_cols].median())

# 4. Fill categorical with mode
for col in categorical_cols:
    # Check if the column has any non-null values before calling mode
    if Telcom[col].nunique() > 0:
        Telcom[col] = Telcom[col].fillna(Telcom[col].mode()[0])
    else:
        # If the whole column is empty, fill with "Unknown"
        Telcom[col] = Telcom[col].fillna("Unknown")

# =========================
#  OUTPUT FOR DATA CLEANING
# =========================

print("---  DATA CLEANING SUMMARY ---")

# 1. Row Check
rows_after = Telcom.shape[0]
print(f"Rows remaining after removing 80% empty rows: {rows_after:,}")

# 2. Column Type Check
print(f"Numeric columns processed: {len(numeric_cols)}")
print(f"Categorical columns processed: {len(categorical_cols)}")

# 3. Missing Value Verification
# This counts how many NaNs are left (should be 0!)
remaining_nans = Telcom.isnull().sum().sum()

if remaining_nans == 0:
    print("\n SUCCESS: All missing values have been filled.")
else:
    print(f"\n WARNING: There are still {remaining_nans} missing values in the dataset.")

# 4. Preview of cleaned numeric values
print("\n---  NUMERIC FILL PREVIEW (Median check) ---")
print(Telcom[numeric_cols[:5]].describe().loc[['50%']])

# 5. Preview of cleaned categorical values
print("\n---  CATEGORICAL FILL PREVIEW ---")
print(Telcom[categorical_cols[:3]].head())

"""# STEP 8: CHURN TARGET"""

print(Telcom.columns.tolist())

# STEP 8: CHURN TARGET LOGIC (Fixed for lowercase 'month')

# 1. Create the pivot table
# Using 'month' (lowercase) and 'avg_revenue_per_user'
activity = Telcom.pivot_table(
    index='mobile_number',
    columns='month',
    values='avg_revenue_per_user',
    aggfunc='sum'
).fillna(0)

# 2. Force column names to strings ('6', '7', '8', '9')
activity.columns = activity.columns.astype(str)

# 3. Define the Churn logic (1 = Churned, 0 = Stayed)
# Logic: Revenue in month 8 (August) > 0 AND Revenue in month 9 (September) == 0
if '8' in activity.columns and '9' in activity.columns:
    activity['churn'] = ((activity['8'] > 0) & (activity['9'] == 0)).astype(int)
else:
    # Fallback in case your months are 6, 7, 8 only
    print("Warning: Month 9 not found. Checking available months:", activity.columns.tolist())

# 4. Map the churn result back to the main Telcom table
# We drop 'churn' first just in case you've run this cell before (prevents churn_x/y)
if 'churn' in Telcom.columns:
    Telcom = Telcom.drop(columns=['churn'])

Telcom = Telcom.merge(activity[['churn']], on='mobile_number', how='left')

# 5. Final verification
print(f"Dataset Churn Rate: {Telcom['churn'].mean():.2%}")
print("\n--- CHURN COUNT SUMMARY ---")
print(Telcom['churn'].value_counts())

"""# STEP 9: CUSTOMER TENURE"""

#  ANALYZING CUSTOMER TENURE (LOYALTY)


# 1. Force 'aon' to be numeric (this handles strings if they exist)
Telcom['aon'] = pd.to_numeric(Telcom['aon'], errors='coerce')

# 2. Fill missing AON values with the median (so we don't get NaN years)
Telcom['aon'] = Telcom['aon'].fillna(Telcom['aon'].median())

# 3. Now perform the division!
Telcom['tenure_years'] = Telcom['aon'] / 365

print("---  MOST LOYAL CUSTOMERS (TOP TENURE) ---")
# Sorting to see who has been with the company the longest
loyal_customers = Telcom.sort_values(by='aon', ascending=False).head(10)
print(loyal_customers[['mobile_number', 'aon', 'tenure_years', 'churn']])

"""# STEP 10: FEATURE ENGINEERING"""

#  FEATURE ENGINEERING

Telcom['total_recharge'] = Telcom['total_recharge_amt'] + Telcom['total_rech_data']
Telcom['total_usage_mou'] = Telcom['total_outgoing_min'] + Telcom['total_ic_mou']


# =========================
# OUTPUT FOR FEATURE ENGINEERING
# =========================

print("---  FEATURE ENGINEERING CHECK ---")

# Let's look at a few rows to make sure the math added up
print("Sample Calculation (First 5 rows):")
cols_to_show = [
    'total_recharge_amt', 'total_rech_data', 'total_recharge',
    'total_outgoing_min', 'total_ic_mou', 'total_usage_mou'
]

# Using .head() to see if the sum looks right
print(Telcom[cols_to_show].head())

print("\n---  NEW FEATURE STATS ---")
# This helps you see the range of your new features
print(Telcom[['total_recharge', 'total_usage_mou']].describe().loc[['mean', 'min', 'max']])

# Quick check for NaNs (math with a NaN results in a NaN)
if Telcom['total_recharge'].isnull().any() or Telcom['total_usage_mou'].isnull().any():
    print("\n WARNING: Some new features have NaN values. Check your source columns!")
else:
    print("\n SUCCESS: New features calculated with no missing values.")

"""# STEP 11: PREPARE TRAINING DATA"""

# We remove IDs, Dates, and the Target from the features
exclude = [
    'churn', 'mobile_number', 'date_last_recharge',
    'date_of_last_rech_data', 'last_day_month', 'service_area_id'
]

X = Telcom.drop(columns=exclude, errors='ignore')
y = Telcom['churn']

# Convert any remaining text columns to numeric codes
for col in X.select_dtypes(include=['object']).columns:
    X[col] = X[col].astype('category').cat.codes

# =========================
# OUTPUT FOR DATA PREPARATION
# =========================

print("---  FEATURE PREPARATION SUMMARY ---")
print(f"Target variable (y) distribution:\n{y.value_counts()}")
print(f"\nTotal Features in X: {X.shape[1]}")

print("\n---  TOP 10 REMAINING FEATURES (X) ---")
print(X.columns[:10].tolist())

print("\n---  DATA TYPE CHECK (First 5 columns) ---")
# This ensures everything is numeric (int or float) and ready for the model
print(X.dtypes.head(5))

# Check for any remaining non-numeric columns
non_numeric = X.select_dtypes(exclude=[np.number]).columns
if len(non_numeric) == 0:
    print("\n SUCCESS: All features are numeric and ready for modeling!")
else:
    print(f"\n WARNING: Still have non-numeric columns: {non_numeric.tolist()}")

"""# STEP 11.5: FINAL SAFETY CLEANING"""

# 1. Check for any remaining NaNs in X
nan_counts = X.isnull().sum()
cols_with_nans = nan_counts[nan_counts > 0]

if not cols_with_nans.empty:
    print("Found NaNs in the following features. Filling them now...")
    print(cols_with_nans)

    # Fill numeric NaNs with the median of each column
    # This handles NaNs created during Feature Engineering (Step 10)
    X = X.fillna(X.median())
else:
    print("No NaNs found in X. You are good to go!")

# 2. Check for NaNs in the target variable y
if y.isnull().any():
    print(f"Warning: Found {y.isnull().sum()} NaNs in target 'y'. Filling with 0 (Non-Churn).")
    y = y.fillna(0)

# 3. Final verification to ensure everything is finite
if not np.isfinite(X).all().all():
    print("Warning: Infinity values detected. Replacing with 0.")
    X = X.replace([np.inf, -np.inf], 0).fillna(0)

print("\n--- SAFETY CHECK COMPLETE ---")

"""# STEP 12 : SPLIT & SCALE-TRAIN AND TEST"""

#  SPLIT & SCALE

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# =========================
# OUTPUT FOR SPLIT & SCALE
# =========================

print("---  DATA SPLIT SUMMARY ---")
print(f"Total Rows in Original Data: {len(X)}")
print(f"Rows in Training Set (80%):  {X_train.shape[0]}")
print(f"Rows in Testing Set (20%):   {X_test.shape[0]}")
print(f"Number of Features (Cols):   {X_train.shape[1]}")

print("\n---  SCALING CHECK (First 2 rows of X_train_scaled) ---")
# This shows the first 2 rows and first 5 columns of the scaled data
# Scaled values usually fall between -3 and 3
print(X_train_scaled[:2, :5])

print("\n---  SPLIT & SCALE COMPLETE ---")

"""# STEP 13: LOGISTIC REGRESSION"""

#  LOGISTIC REGRESSION (Weighted)

# 'balanced' helps the model catch churners in imbalanced data
model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_scaled, y_train)

# Quick EVALUATION
y_pred = model.predict(X_test_scaled)
print("\n--- MODEL PERFORMANCE ---")
print(classification_report(y_test, y_pred))

"""#STEP 14:  RISK SCORING & CLUSTERING USING KMEANS CLUSTERING


"""

# 1. Handle NaNs in X one last time before prediction
# This ensures predict_proba and KMeans don't crash
X = X.fillna(X.median()).replace([np.inf, -np.inf], 0)

# 2. Risk Score: 0 (Safe) to 1 (High Risk)
# Ensure the columns in X match the ones the scaler was trained on
Telcom['Risk_Probability'] = model.predict_proba(scaler.transform(X))[:, 1]

# 3. Clusters: Grouping users by behavior
# FIX: Use lowercase 'month' to match your dataframe
X_for_clustering = X.drop(columns=['month'], errors='ignore')

# Handle any NaNs in the clustering data specifically
X_for_clustering = X_for_clustering.fillna(0)

cluster_scaler = StandardScaler()
X_clust_scaled = cluster_scaler.fit_transform(X_for_clustering)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
Telcom['User_Segment'] = kmeans.fit_predict(X_clust_scaled)

# =========================
# PRINTING THE RESULTS
# =========================

print("\n---  TOP 5 HIGH-RISK CUSTOMERS ---")
# FIX: Changed 'Month' to 'month'
high_risk = Telcom.sort_values(by='Risk_Probability', ascending=False).head(5)
if 'month' in high_risk.columns:
    print(high_risk[['mobile_number', 'month', 'Risk_Probability', 'User_Segment']])
else:
    print(high_risk[['mobile_number', 'Risk_Probability', 'User_Segment']])

print("\n---  CLUSTER (SEGMENT) PROFILES ---")
# Check which columns actually exist to avoid errors in grouping
available_cols = Telcom.columns.tolist()
agg_dict = {'Risk_Probability': 'mean', 'mobile_number': 'count'}

# Only add these if they were successfully created in Step 10
if 'avg_revenue_per_user' in available_cols: agg_dict['avg_revenue_per_user'] = 'mean'
if 'total_usage_mou' in available_cols: agg_dict['total_usage_mou'] = 'mean'
if 'total_recharge' in available_cols: agg_dict['total_recharge'] = 'mean'

cluster_summary = Telcom.groupby('User_Segment').agg(agg_dict).rename(columns={'mobile_number': 'Customer_Count'})

print(cluster_summary)

print("\n---  CHURN BY SEGMENT ---")
if 'churn' in Telcom.columns:
    churn_analysis = Telcom.groupby('User_Segment')['churn'].mean() * 100
    print("Churn Rate per Segment (%):")
    print(churn_analysis)

"""# STEP 14 : DATA VISUALIZATION"""

import seaborn as sns
import matplotlib.pyplot as plt

# Set the visual style for all plots
sns.set_theme(style="whitegrid")

# Create a large figure to hold multiple plots
plt.figure(figsize=(20, 15))

# --- PLOT 1: Churn Distribution ---
# This shows the "Class Imbalance" - how many people stay vs. how many leave.
plt.subplot(2, 2, 1)
sns.countplot(data=Telcom, x='churn', palette='viridis')
plt.title('1. Distribution of Churn (0 = Stayed, 1 = Churned)', fontsize=14)
plt.xlabel('Churn Status')
plt.ylabel('Number of Records')

# --- PLOT 2: Churn Rate by User Segment ---
# This shows which of your behavioral clusters (0, 1, or 2) is the most "dangerous."
plt.subplot(2, 2, 2)
segment_churn = Telcom.groupby('User_Segment')['churn'].mean().reset_index()
sns.barplot(data=segment_churn, x='User_Segment', y='churn', palette='magma')
plt.title('2. Churn Rate by Behavioral Segment', fontsize=14)
plt.ylabel('Churn Probability (0.0 to 1.0)')

# --- PLOT 3: Risk Score Accuracy (High Contrast Version) ---
plt.subplot(2, 2, 3)

# Using 'Set1' for high contrast, or you can use ['#2ecc71', '#e74c3c'] for Green/Red
sns.kdeplot(
    data=Telcom,
    x='Risk_Probability',
    hue='churn',
    fill=True,
    common_norm=False,
    palette='Set1',  # 'Set1' gives very bold, different colors
    linewidth=2
)

plt.title('3. Risk Score Distribution: Churners vs Non-Churners', fontsize=14, fontweight='bold')
plt.xlabel('Model Predicted Risk (0 to 1)')
plt.ylabel('Density')

# Optional: Add a legend to clarify the colors if they aren't clear
plt.legend(title='Status', labels=['Churned (1)', 'Stayed (0)'])

# --- PLOT 4: Revenue vs. Usage by Segment ---
# This helps you understand the "Profile" of your clusters.
# It shows how high-value users (top right) differ from low-value users (bottom left).
plt.subplot(2, 2, 4)
# We take a sample of 5,000 rows so the plot isn't too crowded/slow
sample_df = Telcom.sample(n=min(5000, len(Telcom)))
sns.scatterplot(data=sample_df, x='total_usage_mou', y='avg_revenue_per_user', hue='User_Segment', palette='Set1', alpha=0.6)
plt.title('4. Revenue vs. Usage (Sampled by Segment)', fontsize=14)
plt.xlabel('Total Usage (Minutes of Use)')
plt.ylabel('Average Revenue Per User (ARPU)')

# Adjust layout so titles don't overlap
plt.tight_layout()

# Save the plot for your report
plt.savefig('telecom_churn_visuals.png')
print("Plots generated and saved as 'telecom_churn_visuals.png'!")

"""STEP 15: PREPARING DATA FOR POWERBI EXPORT"""

# 1. Final check: Ensure the filename is clear
output_filename = "telecom_churn_analysis.csv"

# 2. Export the data
Telcom.to_csv(output_filename, index=False)

print(f"\n  DONE! Exported '{output_filename}'")

# 3. Print verification - Fixed 'month' to lowercase
# Also added a check to make sure these columns exist before printing
cols_to_show = ['mobile_number', 'month', 'churn', 'Risk_Probability', 'User_Segment']
existing_cols = [c for c in cols_to_show if c in Telcom.columns]

print("\n--- PREVIEW OF EXPORTED DATA ---")
print(Telcom[existing_cols].head())